### ISSUE TITLE
release v1.1.2

### ISSUE THREAD

**Issue by butonic** [glauth/glauth#110]
The current dev branch has merge conflicts because of conflicting changes in `master` and `dev`. We should get a release out asap.

- [x] if necessary ~~rebase dev &~~ merge dev manually into master to solve any merge conflics
- [x] tag master v1.1.2 locally using `git tag v1.1.2`
- [x]  push tag to github using `git push origin v1.1.2`
  - this will trigger the release build and create a draft release
- [x] write changelog

**Comment by unclesamwk** [comment]
if the readme needs updated, pls doit. thx for this very nice ldap server :-)

**Comment by butonic** [comment]
Following the [quickstart](https://github.com/glauth/glauth#quickstart) works and the new config options have ben added as well. So I think we're good to go!
