### ISSUE TITLE
Look into ansible directory

### ISSUE THREAD

**Issue by benyanke** [glauth/glauth#12]
I have never used ansible, so as maintainer, I'm not sure if it's up to date or even applicable anymore.

Anyone familiar with ansible, I'd love to hear from you.

**Comment by nmcclain** [comment]
I think this is old cruft that should be removed.

It was used for configuring a linux *client* to use LDAP for logins.

**Comment by benyanke** [comment]
Sounds good - that sounds more like the scope of another repo with the ansible client config, at the very least. Removing.
