### ISSUE TITLE
Suggestion: enable wiki for documentation

### ISSUE THREAD

**Issue by poldi1405** [glauth/glauth#127]
I think the documentation could be improved and I think the Wiki-Tab would be just perfect for that. Some things that might be helpful:

- additional information about certain config-sections
- a "how to get started" section
- some small guides

**Comment by butonic** [comment]
Hm, the Wiki is enabled. How so you propose to Organizer it? So you have a good example we could follow?

**Comment by poldi1405** [comment]
I personally like [Sonarr's Wiki](https://github.com/Sonarr/Sonarr/wiki) as it is easy to navigate and has all the relevant sections (configuration, troubleshooting, contributing, ...)

**Comment by butonic** [comment]
I enabled write access to the wiki for peoplewithout push permissions. Let's see how this evolves.

@poldi1405 feel free to add a structure as an Sonarr's Wiki ... looks like a start
