### ISSUE TITLE
unable to build on ubuntu 18.04.4 LTS

### ISSUE THREAD

**Issue by maxilee** [glauth/glauth#130]
hello.
I'm unable to build glauth on ubuntu 18.04.4 LTS.
there is error when I run "make getdeps"

I've tried both branches : master and dev. but both branches gives different errors : 

master branch : 
# make getdeps
go get -d ./...
package github.com/glauth/glauth/pkg/assets: cannot find package "github.com/glauth/glauth/pkg/assets" in any of:
        /usr/lib/go-1.10/src/github.com/glauth/glauth/pkg/assets (from $GOROOT)
        /root/go/src/github.com/glauth/glauth/pkg/assets (from $GOPATH)
package github.com/glauth/glauth/pkg/gologgingr: cannot find package "github.com/glauth/glauth/pkg/gologgingr" in any of:
        /usr/lib/go-1.10/src/github.com/glauth/glauth/pkg/gologgingr (from $GOROOT)
        /root/go/src/github.com/glauth/glauth/pkg/gologgingr (from $GOPATH)
Makefile:53: recipe for target 'getdeps' failed
make: *** [getdeps] Error 1

dev branch: 
# make getdeps
go get -d ./...
package github.com/glauth/glauth/pkg/assets: cannot find package "github.com/glauth/glauth/pkg/assets" in any of:
        /usr/lib/go-1.10/src/github.com/glauth/glauth/pkg/assets (from $GOROOT)
        /root/go/src/github.com/glauth/glauth/pkg/assets (from $GOPATH)
package github.com/glauth/glauth/pkg/gologgingr: cannot find package "github.com/glauth/glauth/pkg/gologgingr" in any of:
        /usr/lib/go-1.10/src/github.com/glauth/glauth/pkg/gologgingr (from $GOROOT)
        /root/go/src/github.com/glauth/glauth/pkg/gologgingr (from $GOPATH)
Makefile:53: recipe for target 'getdeps' failed
make: *** [getdeps] Error 1

on fedora 31 I've build glauth64 without any problems ...

**Comment by Fusion** [comment]
This was tested and works in the dev branch. @butonic did make some changes w/r/t logging.
