### ISSUE TITLE
shadowaccount on ubuntu 18.04.4 LTS

### ISSUE THREAD

**Issue by maxilee** [glauth/glauth#131]
I'm using on few machines ubuntu 18.04.4 and I've found that ubuntu searches LDAP for objectClass=shadowAccount  when user login to the system.

in source code in file "pkg/handler/config.go" in line 207 there is code which returns results only when LDAP client search for objectClass=posixaccount or empty filter.

'case "posixaccount","": '

this can be changed to : 

'case "posixaccount", "shadowaccount","":'

then results will be returend when ldap client specify filter "objectClass=shadowAccount"

**Comment by butonic** [comment]
fixed with https://github.com/glauth/glauth/pull/136
