### ISSUE TITLE
Config file hot reload doesn't work

### ISSUE THREAD

**Issue by weibeld** [glauth/glauth#132]
Just downloaded [v1.1.2](https://github.com/glauth/glauth/releases/tag/v1.1.2) and tried with a config file containing:

```cfg
watchconfig = true

[backend]
  datastore = "config"
  baseDN = "dc=glauth,dc=com"
```

When editing and saving the config file (e.g. adding a user), nothing happens. Actually, GLAuth should reload the config file as defined in the [code](https://github.com/glauth/glauth/blob/master/glauth.go#L150).

**Comment by fanlix** [comment]
v1.1.2 reload not works. ubuntu 20.04.2

**Comment by fanlix** [comment]
figure this out, it's fsnotify lib & vim/editor/fs problem.  origin issue: https://github.com/fsnotify/fsnotify/issues/17

* pure write works
* `cp xx.cfg xx.cfg` works
* `vim xx.cfg`, use  `:w` to save, not works. 
  * also cause fsnotify quit.
  * set nobackup in vim, works. but we never do this.
 
## answer
* `./glauth -c config.cfg`
* edit a copy of config file `config.cfg.edit`
* when finished , `cp config.cfg.edit config.cfg`

**Comment by Fusion** [comment]
Merged in.
