### ISSUE TITLE
Reload Config File Without Process Restart

### ISSUE THREAD

**Issue by benyanke** [glauth/glauth#14]
Build a way reload the config file, so that additional users can be added without downtime. Perhaps sending a signal to the process.

Additionally, some of the infrastructure could even be used to add another option to poll the file and update every several seconds if the file changes - this could similarly be used to allow the s3 option to be live-updating (polling for updates every - say - 5 minutes).

**Comment by ryskov** [comment]
PR #58 is now merged into the dev branch

**Comment by butonic** [comment]
reloading works, but there is still a warning in the log
```
17:30:20.550795 func1 ▶ WARN 038 Could not reload config: LDAPS was enabled but no certificate or key were specified: please disable LDAPS or use the 'cert' and 'key' optionsHolding on to old config
```

changes to users are still picked up and the ldaps port continues to work (a certificate is available)
