### ISSUE TITLE
ARM (multiarch) docker image

### ISSUE THREAD

**Issue by yajo** [glauth/glauth#141]
I'd love to use this project dockerized in the raspberry.

Is this on the roadmap? Can I help?

cc @joao-p-marques

**Comment by brettinternet** [comment]
I don't see ARM support in the docker tags: https://hub.docker.com/r/glauth/glauth/tags. Am I mistaken?

**Comment by Fusion** [comment]
Give me a bit of time to figure this out, thanks. Cross building has been a thorn in my side.

**Comment by Fusion** [comment]
OK I will soon make this available. I have figured it out.

**Comment by brettinternet** [comment]
@Fusion thank you for your attention to this. I don't see any multiarch images pushed to https://hub.docker.com/r/glauth/glauth/tags, but I think the multiarch support will release with v2.2.0? Should we track this in https://github.com/glauth/glauth/issues/257 or do you prefer for users host their own images?

I wonder if we could also include a nightly tag to allow users to test your release candidates with containerized setups? https://github.com/docker has some very handy Github Actions to support different releases like this.
