### ISSUE TITLE
uidnumber or unixid?

### ISSUE THREAD

**Issue by Yajo** [glauth/glauth#144]
In the sample I see usage of `unixid`: https://github.com/glauth/glauth/blob/a92f9a7028fdf68952ffbed4958167b928dbc483/sample-simple.cfg#L70

But in the docs, it says [you must use `uidnumber`](https://github.com/glauth/glauth/tree/a92f9a7028fdf68952ffbed4958167b928dbc483#required-fields).

So, which one is right? :confused:

**Comment by butonic** [comment]
`unixid` in the config file becomes `uidnumber` in the LDAP api. I find this a little confusing as well, PR welcome.

**Comment by fgma** [comment]
@butonic See my PR.
