### ISSUE TITLE
Not able to connect glAuth server

### ISSUE THREAD

**Issue by ronikb** [glauth/glauth#147]
![glauth](https://user-images.githubusercontent.com/805095/88516591-26a84100-d00b-11ea-86dd-3720fb76f888.JPG)

As part of my evaluation of this tool, I just downloaded the latest binary and started it using the sample config file you specified here in the document. Looks like the service started but i couldn't able to connect. Attached the screenshot included my troubleshooting steps also.  I am not sure what I am wrong with this configuration. It will be good to give some light about this issues.Thanks in advance

Regards
Roni Baby

**Comment by lutzhorn** [comment]
Disable TLS in the `sample-simple.cfg` here by setting `enabled = false`. Or make sure you have the certificates.

https://github.com/glauth/glauth/blob/a92f9a7028fdf68952ffbed4958167b928dbc483/sample-simple.cfg#L34-L38

**Comment by Fusion** [comment]
Resolved by ghost. Thanks!
