### ISSUE TITLE
Unable to integrate it with PAM

### ISSUE THREAD

**Issue by kang-makes** [glauth/glauth#162]
I have enough services in my home lab to have a LDAP to try to centralize users but now enough to mount a full pledge LDAP like slapd or whatsever.

I was doing a test on some VMs to test this and worked with some services like next cloud and nginx-ldap but now I'm trying to integrated with Linux at PAM level.

I think Glauth is correctly configured:
```toml
[ldap]
  enabled = true
  listen = "0.0.0.0:3893"
[ldaps]
  enabled = false
[api]
  enabled = true
  tls = false # enable TLS for production!!
  listen = "0.0.0.0:5555"
  cert = "cert.pem"
  key = "key.pem"

debug = true

[backend]
  datastore = "config"
  baseDN = "dc=h"

################# USERS #################
[[users]]
  name = "root"
  givenname = "root"
  unixID = 0
  primaryGroup = 5501
  otherGroups = [ 5503 ]
  loginShell = "/bin/bash"
  homeDir = "/root"
  passsha256 = REDACTED

# Home users
[[users]]
  name = "kang"
  unixID = 10000
  primaryGroup = 5501
  otherGroups = [ 5503 ]
  loginShell = "/bin/bash"
  homeDir = "/home/kang"
  passsha256 = REDACTED

################# GROUPS #################
[[groups]]
  name = "home"
  unixid = 5501
```
`% ldapsearch -x -H ldap://glauth.s -D cn=root,ou=home,dc=h -w "$pass" -b dc=h cn=kang`
```
# extended LDIF
#
# LDAPv3
# base <dc=h> with scope subtree
# filter: cn=kang
# requesting: ALL
#

# kang, home, h
dn: cn=kang,ou=home,dc=h
cn: kang
uid: kang
ou: home
uidNumber: 10000
accountStatus: active
objectClass: posixAccount
objectClass: shadowAccount
loginShell: /bin/bash
homeDirectory: /home/kang
description: kang
gecos: kang
gidNumber: 5501
memberOf: cn=home,ou=groups,dc=h
shadowExpire: -1
shadowFlag: 134538308
shadowInactive: -1
shadowLastChange: 11000
shadowMax: 99999
shadowMin: -1
shadowWarning: 7

# search result
search: 2
result: 0 Success

# numResponses: 2
# numEntries: 1
```

So I configure PAM:
`# cat /etc/nsswitch.conf`
```
passwd:         files ldap
group:          files ldap
shadow:         files ldap
gshadow:        files ldap
```
`# cat /etc/libnss-ldap.conf `
```
host glauth.s
base dc=h
ldap_version 3

rootbinddn cn=root,ou=home,dc=h
bindpw secret
```
`# cat /etc/libnss-ldap.secret`
```
REDACTED
```
It seems to work:
`# getent passwd | grep kang`
```
kang:x:10000:5501:kang:/home/kang:/bin/bash
```
`# getent group | grep kang`
```
home:*:5501:kang,root,kang,root
```

But when I try to the a passwd with `getent passwd` o simply `su` it fails.
`# getent shadow | grep kang | wc -l`
```
0
```
These are the errors I find in the logs:
```
2020/12/09 20:10:53 handleSearchRequest error LDAP Result Code 1 "Operations Error": Search Error: unhandled filter type: shadowaccount [(&(objectClass=shadowAccount)(uid=kang))]
2020/12/09 20:10:53 handleSearchRequest error LDAP Result Code 1 "Operations Error": Search Error: unhandled filter type: shadowaccount [(&(objectClass=shadowAccount)(uid=kang))]
2020/12/09 20:10:54 handleSearchRequest error LDAP Result Code 1 "Operations Error": Search Error: unhandled filter type: shadowaccount [(&(objectClass=shadowAccount)(uid=kang))]
2020/12/09 20:13:02 handleSearchRequest error LDAP Result Code 1 "Operations Error": Search Error: unhandled filter type: shadowaccount [(objectClass=shadowAccount)]
2020/12/09 20:13:58 handleSearchRequest error LDAP Result Code 1 "Operations Error": Search Error: unhandled filter type: shadowaccount [(objectClass=shadowAccount)]
2020/12/09 20:15:39 handleSearchRequest error LDAP Result Code 1 "Operations Error": Search Error: unhandled filter type: shadowaccount [(objectClass=shadowAccount)]
```

Any hint of when to start to debug to see if I can help?

OS: Debian 10
Simply install `libnss-ldap` and `libpam-ldapd` on a fresh machine and change the files I mentioned to reproduce this bug/feature request.

**Comment by kangco-de** [comment]
I have downloaded and compiled `dev` branch in order to test if this fails and try to fix it and apparently it was fixed.

I've uploaded an image to my dockerhub repository while this new version is released: `kangcode/glauth:v2.0-dirty-faed82a`

I'll keep this bug open until v2.0 is released in order to follow it.

**Comment by butonic** [comment]
cool. I am planning a release in 3 weeks after I attended a conference.

**Comment by Fusion** [comment]
I also created a Wiki page that describes two different ways to implement PAM auth using GLAuth:

https://github.com/glauth/glauth/wiki/SSH-PAM-(Pluggable-Authentication-Modules)-configuration

**Comment by kang-makes** [comment]
I think this is still a issue until I'll keep this bug open until v2.0 is released...

**Comment by Fusion** [comment]
Fair enough. Re-opening until v2 release.

**Comment by pratikbalar** [comment]
@kang-makes  any updates ?

**Comment by ICQFan4ever** [comment]
Working well in my homelab.
But I've created groups with names "posixAccount" and "shadowAccount" then added them as groups [... ...] in [[user]] section

**Comment by kang-makes** [comment]
Sorry for the delay. Too much life and pandemic issues around me.

Yes. The latest version worked like a charm.

Closing.

**Comment by antton** [comment]
Hi @kang-makes , @D13410N3 and @Fusion, 

Did you integrate with SSSD or in an old PAM way?

Did you use LDAPS?

If anyone of you can help with a config.cfg example I would appreciate!

I'm still stuck trying to configure it properly.

Thanks!
