### ISSUE TITLE
Link to a public chat, eg gitter or matrix

### ISSUE THREAD

**Issue by butonic** [glauth/glauth#166]
I created a [glauth room](https://matrix.to/#/#glauth:matrix.org?via=matrix.org) in matrix because I don't have the glauth organization powers to add gitter. We should still add a link to the chat in the README. PR welcome!

**Comment by butonic** [comment]
Maybe ![Matrix](https://img.shields.io/matrix/glauth:matrix.org)

**Comment by Fusion** [comment]
I believe you now have org access? If so would you still consider adding Gitter?

I joined the matrix room in the meantime...
