### ISSUE TITLE
I need access to the Glauth organization

### ISSUE THREAD

**Issue by butonic** [glauth/glauth#172]
When @benyanke added me as an admin to the Glauth repo, he did not add me to the Glauth organization. I'd like to fix travis and create a gitter chat before the next release but that requires access to the organization.

I tried contacting @benyanke but he has not reacted for a week. I am opening this issue as another way to contact him and let everyone know that I want to move forward.

After the release I would like to make some changes:
- Have a minimal binary that only supports read only backend like the config, maybe .htpasswd and the posix /etc/shadow file ... Maybe pam, but I'd like to keep CGO out of this version. The binary should be as small as possible.
- Have a full fledged version that supports databases like postgres, mysql and also sqlite. It will also have a web ui and ms graph based rest/json api.
- Together with kopano konnectd both versions could be a minimal / small openid connect identity provider. Maybe even bring OIDC to raspberry pi owners and redecentralize identity management.

I hope ben reacts soon, otherwise we need to find another home organization for Glauth.

Let me know what you think.

_Full disclosure: In my day job I am the lead architect for ownClouds https://github.com/owncloud/ocis and we plan to move the ui and api we developed for the accounts service into Glauth to further focus on file sync and share. We would love to see Glauth and konnectd used in more projects as the drop in user management solution. It should cover 80% of all use cases and if really needed / outgrown it can be switched for keycloak, ping or whatever._

**Comment by benyanke** [comment]
I'm sorry for the delay on this. I've had very little free time for side projects at this time.

Let's connect up out of band, I'll get you the needed access.

**Comment by butonic** [comment]
Thx @benyanke! And no hard feelings! I'll work on the release.
