### ISSUE TITLE
Change passwords

### ISSUE THREAD

**Issue by miathedev** [glauth/glauth#174]
More like question, not a issue. Im tinkering with glauth.
I tryed to change a password with ldappasswd.

**My config:**
https://paste.ubuntu.com/p/RZ69qfjT2J/

Im able to search for a specific type of user:

```
#Search for admins
ldapsearch -LLL -H ldap://localhost:3893 -D cn=adminuser,ou=megaadmin,dc=glauth,dc=com -w dogood -x -bdc=glauth,dc=com cn=adminuser

#Search for normal users
ldapsearch -LLL -H ldap://localhost:3893 -D cn=normaleruser,ou=megauser,dc=glauth,dc=com -w dogood -x -bdc=glauth,dc=com cn=normaleruser
```

But! I wanted to change a password for the user _"adminuser"_ over ldaps

```
ldappasswd -H ldap://localhost:3893 -x -D "cn=adminuser,ou=megaadmin,dc=glauth,dc=com" -W -S
New password: 
Re-enter new password: 
Enter LDAP Password: 
Result: Protocol error (2)
Additional info: Protocol Error
```

Did someone manage to change a users password over ldaps? Or does someone know what i made wrong?

With kind regards,
Mia

**Comment by butonic** [comment]
The LDAP libraries used by glauth do not support write operations like changing passwords: https://github.com/nmcclain/ldap#not-implemented
