### ISSUE TITLE
Glauth - Web UI

### ISSUE THREAD

**Issue by sonicnkt** [glauth/glauth#176]
Hi, 
i wanted to tell you about a small project i have been working on in the last two weeks.
Have been using glauth now for a few months and i love the simple and quick setup. 
I also wanted to use glauth at work for unifying the authentication of a few services im hosting but since its read-only there was no way for users to change their name/email or password on their own.

Since i started to learn flask (python) i thought it shouldn't be to hard to create a small web interface that generates a glauth compatible config file and i started tinkering.

Well after two weeks now i want to make it available to the public. 

![image](https://user-images.githubusercontent.com/5454622/113170470-e0187f80-9246-11eb-80d0-f44d028232e5.png)

It is a small web interface with its own db but generates a new glauth config file whenever there is a change to the data.
Using the `watchconfig` option in glauth the file is then reread and the changes take effect. 
You cant change the config.cfg manually atm, those change would be overwritten by the management ui.
A config parser is planned tho for the initial import.

Currently the app consists of a small end user interface where users can register (after invite) and login to change their names, mail address or password.
There is also a password recovery function integrated.

Besides that it supports  the following glauth user options (with validations for many):
 - name
 - unixid
 - givenname
 - sn (surname)
 - mail
 - disabled (active)
 - passsha256
 - primarygroup
 - othergroups

Groups are of course supported as well, primarygroups have a special flag so only groups with that flag can be assigned as primary groups.
Groups can be included in others groups besides primary groups which can not be included in other groups but can include them.

The admin interface allows you to manage all this and is only accessible to users that are a member of the "glauth ui admin" group which can be configured using environment variables. 

Like i said it does not support all config options yet that glauth has as i only implemented those that i really need for now. 

The documentations is not complete yet but i added some instructions (docker) to get it working quickly and to play arround with it.

If the app starts with an empty db it will generate a sample dataset.
If you have any feedback please post them in this issue or even better in its own repository.

**https://github.com/sonicnkt/glauth-ui**

**Comment by Fusion** [comment]
This is fantastic.

Note that, in another issue, someone was requesting password policies (my guess is: expiration, acceptable password complexity, etc) I wonder if you would have time to add this feature.

glauth itself is easy to configure and use, and thus focuses on the LDAP queries aspect. A project that offers account lifecycle management is a perfect complement.

**Comment by sonicnkt** [comment]
This is a good idea, if glauth stays readonly it would be better to add those features to the interface instead as a normal user wouldnt be able to change those otherwise anyway. 

I will put this on my todo. havent touched it in a while as i was busy with other stuff (and it was working well enough for my production use ;) ). 

a good addition for glauth regarding password would be stronger (or configureable) hashes tho (maybe add salts?), i think this was requested before tho.

**Comment by Fusion** [comment]
Yes, stronger hashing and unique salts are also likely to happen :)

**Comment by Fusion** [comment]
Strong hashing and unique salts were added.

I even got to contribute a little bit to the ui project (PR) :)

Closing and will definitely find a way to mention the project in future documentation.
