### ISSUE TITLE
High-Availability setup

### ISSUE THREAD

**Issue by LecrisUT** [glauth/glauth#177]
Is it possible to setup a few glauth LDAP servers behind a load-balancer or any other failover method?

**Comment by lukasmrtvy** [comment]
Related https://github.com/glauth/glauth/issues/37

**Comment by benyanke** [comment]
Yes, this is completely doable. glauth is read-only, so there's no reason you couldn't load multiple instances with the same config file behind a TCP load balancer, or DNS round-robin. As long as the same config is the same, youc an do HA with no issue.

**Comment by benyanke** [comment]
@lukasmrtvy not sure if this is actually related - this ticket is requesting info on HA configuration, #37 is documenting the need for some additional integration testing to run in CI.
