### ISSUE TITLE
Password policies supported ?

### ISSUE THREAD

**Issue by patademahesh** [glauth/glauth#178]
Is password change policy supported in glauth?

**Comment by Fusion** [comment]
Not one of the project's current goals.

IMO, password policies should be external to glauth's role as a password "consumer", rather than "producer"

This does not mean that a companion project/tool should not exist.

**Comment by Fusion** [comment]
If complete account lifecycle management is what you are after, I would recommend a heavier solution, such as https://www.freeipa.org/ (I use it as well as GLAuth and it works great in an enterprise environment, when advanced features such as account management or AD federation are needed)
