### ISSUE TITLE
Suggestion: add bcrypt / Argon2 password hashing

### ISSUE THREAD

**Issue by sbrl** [glauth/glauth#179]
SHA256 isn't particularly good as a password hashing algorithm, because it can be quite easily brute forced. I suggest implementing either bcrypt or Argon2 /, Argon2i, because both of these algorithms have a variable cost that can be adjusted to avoid the issue.

**Comment by Fusion** [comment]
Good point.

Will be addressed as part of https://github.com/glauth/glauth/issues/3
