### ISSUE TITLE
Add nested groups

### ISSUE THREAD

**Issue by woopstar** [glauth/glauth#18]
We have added the option to include nested groups:

https://github.com/pasientskyhosting/glauth/commit/0a7cc23177391630c466694432d50fb50428e0c1

**Comment by benyanke** [comment]
Would you be willing to submit a PR for this? I'd love to do a full test and implement if possible. We also have some new features I've added so you might find rebasing on our current version in this new repo could be helpful for you as well!

**Comment by woopstar** [comment]
We will look into it. We just added OTP validation and support for yubikeys.

**Comment by benyanke** [comment]
That is fantastic - I'd love to pull these features  into the main repo with PRs if you're willing. I've recently taken over maintaining this, and looking to add more features.

**Comment by benyanke** [comment]
nested group support was added a while back using the `includegroups` key in a group's config.
