### ISSUE TITLE
OU and primary posix group have to be the same?

### ISSUE THREAD

**Issue by surfrock66** [glauth/glauth#180]
This isn't an issue but a point of clarification; I didn't see anywhere else to ask questions.

Ideally in my environment primary group would be the user group for that user, but it looks in glauth primary group and OU are the same?  Am I understanding that correctly?

**Comment by candlerb** [comment]
As far as I can tell, that's correct (see also #181).  Which means that if a user changes their primary group, their DN changes too.

**Comment by Fusion** [comment]
Yes, I can confirm that this is both correct and tied to their primary group.
