### ISSUE TITLE
ldap filter `memberOf` does not work

### ISSUE THREAD

**Issue by Tony2** [glauth/glauth#186]
I use glauth w/ ldap backend. The filter using `memberOf` doesn't seem to work. Example:
```
ldapsearch -H ldaps://ldap-proxy.example.com:636 -b dc=example,dc=com -D uid=abc,cn=users,dc=example,dc=com -x -w PASS '(memberOf=cn=admin,cn=groups,dc=example,dc=com)'
```

The same query works with the ldap backend.

**Comment by Fusion** [comment]
What OS are you running your tests on? I could send you a recent dev build; I would like to know if some fixes I added to the proxying feature would address this issue.

**Comment by hth2** [comment]
Linux 64bit. I am happy to give it a try.

**Comment by Fusion** [comment]
Cool. Here it is: https://mega.nz/file/11gAzTSD#n_zgVr-AVPYiJoas27w3D61DOYo-4F1rdTlIxqbDWXc

**Comment by pratikbalar** [comment]
I was facing this same `memberOf` issue for retrieving groups in DexIDP,

**Comment by Fusion** [comment]
As I suspected, this is partially fixed.
I injected the requested attribute in the server's response so that the LDAP library would not filter it out.
Now, I need to consider recursive filters like this "and" clause in your example. This is going to be fun.

**Comment by Fusion** [comment]
Pushed to a "fix" branch. Hoping to get it reviewed by more eyeballs before I merge it in.

```
> ldapsearch -LLL -H ldap://localhost:3893 -D cn=admin,dc=glauth,dc=com -w password -x -bdc=glauth,dc=com  "(memberOf=cn=
superheros,ou=groups,dc=glauth,dc=com)"

dn: cn=johndoe,cn=superheros,ou=users,dc=glauth,dc=com
givenName: John
sn: Doe
cn: johndoe
uid: johndoe
userPassword:: e01ENX03TW1XUWVMcENKZnE0WWxCVnVFc1ZBPT0=
gidNumber: 5501
homeDirectory: /home/users/johndoe
objectClass: inetOrgPerson
objectClass: posixAccount
objectClass: top
uidNumber: 5002
memberOf: cn=superheros,ou=groups,dc=glauth,dc=com

> ldapsearch -LLL -H ldap://localhost:3893 -D cn=admin,dc=glauth,dc=com -w password -x -bdc=glauth,dc=com  "(&(objectClass=*
)(memberOf=cn=superheros,ou=groups,dc=glauth,dc=com))"

dn: cn=johndoe,cn=superheros,ou=users,dc=glauth,dc=com
givenName: John
sn: Doe
cn: johndoe
uid: johndoe
userPassword:: e01ENX03TW1XUWVMcENKZnE0WWxCVnVFc1ZBPT0=
gidNumber: 5501
homeDirectory: /home/users/johndoe
objectClass: inetOrgPerson
objectClass: posixAccount
objectClass: top
uidNumber: 5002
memberOf: cn=superheros,ou=groups,dc=glauth,dc=com
```

**Comment by fanlix** [comment]
glauth parsed` [[groups]]` to `ou`, so this works:
`(memberOf=cn=superheros,ou=groups,dc=yq16,dc=fun)`
this does not work
`(memberOf=cn=superheros,cn=groups,dc=yq16,dc=fun)`

**Comment by Fusion** [comment]
Hi @fanlix please note that we are discussing the LDAP backend. Your comment on the config backend is correct, of course.
