### ISSUE TITLE
Soft Fork Time?

### ISSUE THREAD

**Issue by Fusion** [glauth/glauth#187]
@benyanke @butonic @Zenithar so, after more than a year of trying, and getting in side conversations with folks who would really like to see some stuff improved, here we are.

What do you guys think? Should we create a "soft fork" (I don't mean to be rash so I would have no problem working on a fork that could later be re-incorporated in the main repo) and start reviewing pull requests as well as bug reports?

Note that, ideally, I would not be alone performing these tasks! @butonic I believe that you represent another FOSS project, so maybe you guys could help if you plan on using glauth? Anyone else is also welcome, of course.

That is, if you think it is time for a fork. If not, I will keep slowly drifting away in my own private fork and I have a feeling I'm not alone ;)

**Comment by benyanke** [comment]
I'd love to see the project continue mainline development without needing a ton of forks. I sent you an email, let's continue out of band.

We can figure something out I'm sure.

**Comment by benyanke** [comment]
Hi Fusion,

After our out of band discussion, you have been added as a project maintainer. Thank you for your willingness to help continue this project forward!

**Comment by butonic** [comment]
@Fusion @benyanke sorry for my lack of responsiveness. Yes my main work is on owncloud/ocis. And we rely on glauth there. The currend glauth/dav branch should probably be released asap. The question is the direction of glauth in general. I'd really like to keep it small. maybe even without a web ui so you could just use it in ci or for small deployments with a file based user backend.

While digging into the used ldap libraries I came to the conclusion that write support really should not be part of glauth, as the upstream libs don't really support it. 

The kopano guys tried to carve out the working bits and restarted an ldap lib: https://github.com/libregraph/idm/tree/master/pkg/ldapserver

so ... yeah there is movement and the best way of contact is probably https://app.element.io/#/room/#glauth:matrix.org

**Comment by Fusion** [comment]
I agree with you that small is beautiful :)

Well, it is:
- manageable
- faster to build
- easier to configure
- more secure (reduced attack surface)
- easier to compose

Re: Upstream library limitations

I too did notice some limitations in the LDAP library, not all of them having to do with writes. In some cases, I had to work around in my code to make it compatible with more picky clients such as Fortigate firewalls (which is why my recent commit covers a bit more ground that I would like for a single commit)

Re: Write capabilities

There are many ways to write data to an LDAP server, and I agree that Glauth's purpose, as I understand it anyway, is to consume that data to make it easy for clients to provide authentication/authorization, etc.

Re: Modularity

While implementing plugin support for my backends, I realized that plugins may never be considered a first class citizen feature by the language's authors. They have to be built at the same time as the main app (more or less), they will never work on Windows, etc.

IIRC, Hashicorp wrote their own version of plugins, based on socket communication. I expect the tradeoff to be performance vs flexibility. Don't know if you guys have any idea on this topic, but I think that keeping Glauth focused means that at some point plugin support should become an official thing?

Build and Releases Process

I created a Wiki page to explain how CI can be performed locally, before pushing to Github. Now, what branching workflow do you recommend? Developing features in feature branches and merging to the dev branch? Or pull requests?

Also, what's your position w/r/t releases? Last one was more than a year ago and it looks like you've been working on 2.0 for a long time. Do you know what you would want in that release?

**Comment by Fusion** [comment]
I joined that room but it feels a bit lonely in there ;)

I also created a few entries in the Wiki, and created a couple feature branches where I could use some wise input!
