### ISSUE TITLE
Need fix Travis CI API wiring

### ISSUE THREAD

**Issue by Fusion** [glauth/glauth#193]
Hi @benyanke and @butonic I would like to bring to your attention that Travis CI stopped performing builds @ travis.org since the 15th. As a result no pull request can be reviewed.

Also it's been a bit difficult to get hold of you guys (I know it's part of the game!) but since I do not have access to the project's settings I cannot update branch constraints or I would have fixed the issue myself.

Additionally I would need to know how we are going to prepare a release.

Cheers!

**Comment by benyanke** [comment]
It probably doesn't make much sense to have me hook it up under my own name again, but you have project admin now, so you should be able to just re-set it up using the existing travis config in the repo. The only thing that'll probably break is the "release" bit at the bottom, which never fully worked anyways.

**Comment by benyanke** [comment]
For what it's worth, it only ever did testing, not any pushing anywhere, so it can be setup by anyone using the in-repo config.

**Comment by Fusion** [comment]
Thank you. 
Yes, I setup travis-ci.com to work against the org/repo. It was a bit of a challenge but I think/hope I got it right (the secret was to remove the old mandatory check, run an integration test once with the test as an option, then, github having learnt about that new hook, add it back to the branch requirements)
Regarding the topic of releases, do you want to work together on preparing a release, or do you prefer me to do it on my own?

**Comment by benyanke** [comment]
Feel free to go for it. Beyond the typical testing steps, all I really do is locally compile and then upload the binaries to the release entity in GitHub.

**Comment by Fusion** [comment]
OK thanks.
