### ISSUE TITLE
glauth seems to work fine, but with syslog reports many "ping failed" errors

### ISSUE THREAD

**Issue by Tony2** [glauth/glauth#197]
my glauth instance seems to work fine, except that in syslog I see many errors like following:

```
Jul 26 09:40:01 vm-ldap-proxy /usr/local/bin/glauth64[183505]: 09:40:01.422597 ping ▶ ERRO 008 Server 192.168.50.103:7389 ping failed: LDAP Result Code 200 "": EOF
Jul 26 09:40:01 vm-ldap-proxy /usr/local/bin/glauth64[183505]: 09:40:01.422693 ping ▶ DEBU 009 Server health: []handler.ldapBackend{#012    {Scheme:"ldaps", Hostname:"192.168.50.103", Port:7636, Status:1, Ping:4243580},#012    {Scheme:"ldap", Hostname:"192.168.50.103", Port:7389, Status:0, Ping:0},#012}
```

my glauth.cfg has
```
debug = false
syslog = true
```

and my ldap backup listens on 7389 (plain) and 7636 (ssl).  I can run ldapsearch on the glauth server against the backend ldap.

I would like to get rid of those messages in syslog. Any hint please?

**Comment by Fusion** [comment]
Logging levels are not currently configurable beyond "debug" -- this is something that will eventually need to be made a bit more flexible but from what I am seeing in the existing code, Butonic had a real ball wiring some interesting pipes together :)

Do you know why you are seeing these messages? Does you backend actually stop responding on occasion?

**Comment by Tony2** [comment]
I get these msgs regularly; both glauth and the backend seems to work fine from end-user POV.

**Comment by Fusion** [comment]
I reviewed the code and from my tests, this works as designed. Closing.
