### ISSUE TITLE
User serviceuser primary group is not svcaccts.

### ISSUE THREAD

**Issue by blasphemite** [glauth/glauth#208]
I was trying to setup with custom config and kept getting error `primary group mismatch` so I tried example config and am still getting errors.

Using Docker Hub image v1.1.2 with quickstart example config.

Using example `ldapsearch -LLL -H ldap://localhost:3893 -D cn=serviceuser,ou=svcaccts,dc=glauth,dc=com -w mysecret -x -bdc=glauth,dc=com cn=hackers` 

Returns error `ldap_bind: Invalid credentials (49)`

And logs `Bind WARN 007 Bind Error: User serviceuser primary group is not svcaccts.`

Relevant portions of the example config: 
```
[[users]]
  name = "serviceuser"
  mail = "serviceuser@example.com"
  uidnumber = 5003
  primarygroup = 5502
  passsha256 = "652c7dc687d98c9889304ed2e408c74b611e86a40caa51c4b43f1dd5913c5cd0" # mysecret
```
```
[[groups]]
  name = "svcaccts"
  gidnumber = 5502
```

**Comment by Fusion** [comment]
This is unsettling, for sure.
Note that your config file reflects a syntax that is more recent than the one used in v1.2.2, which is now quite outdated.
I apologize for the confusion as it looks like the most recent release (2.0.0 RC1) has not been pushed to the Docker hub. I'll check what is needed to push it successfully.

**Comment by Fusion** [comment]
@blasphemite Would you mind pulling the latest "latest" image and trying again?

**Comment by blasphemite** [comment]
Sample config & my customized config seem to now be working with v2.0.0. Thanks!

**Comment by Fusion** [comment]
Excellent. Thanks for taking the time to confirm!
