### ISSUE TITLE
DOC: Update to include new v2.0.0 database example configuration

### ISSUE THREAD

**Issue by techjutsu-mikeb** [glauth/glauth#220]
The README or documentation does not include examples on how to use the new database plugin.
Can example configuration be added to the README?

**Comment by Fusion** [comment]
Hi Mike. There is a README in the directory where the plugins are:
https://github.com/glauth/glauth/tree/master/pkg/plugins

Let us know if it's not good enough!

**Comment by techjutsu-mikeb** [comment]
Perfect - didn't realize there was a plugins specific README and example config.
Thanks for the quick response.
