### ISSUE TITLE
Admin UI for glauth

### ISSUE THREAD

**Issue by gaby** [glauth/glauth#222]
Are there any plans to introduce an admin web ui for glauth?

**Comment by Fusion** [comment]
Gaby, are you referring to something like this: https://github.com/sonicnkt/glauth-ui

**Comment by gaby** [comment]
> Gaby, are you referring to something like this: https://github.com/sonicnkt/glauth-ui

Exactly what I am ooking for, just afraid the project will get abandone, since it's run by one person.

**Comment by Fusion** [comment]
It is a valid concern. Nils, the UI project maintainer, is still actively working on it.

All I can tell you is that many projects (such as this one) start with one maintainer then, through growth, attract more contributors.

Of course, the worst case scenario (the project being abandoned) is a possibility. The silver lining being that:
- This is open source and someone else may take over
- There is nothing proprietary and therefore, should that project die, you could keep configuring GLAuth using native tools

**Comment by gaby** [comment]
Sounds good, looking forward to using this. :-)
