### ISSUE TITLE
Missing assets package and incorrect module path for v2

### ISSUE THREAD

**Issue by C0rby** [glauth/glauth#226]
I wanted to update the glauth version we use in [oCIS](https://github.com/owncloud/ocis/) but failed for two reasons:

```
❯ go get github.com/glauth/glauth@v1.1.2
github.com/glauth/glauth imports
	github.com/glauth/glauth/pkg/frontend imports
	github.com/glauth/glauth/pkg/assets: cannot find module providing package github.com/glauth/glauth/pkg/assets
```
The assets package is missing. I know it is being generated when running `make bindata` but AFAIK that isn't possible when you are using glauth as a library like we are.

The second reason:
```
❯ go get github.com/glauth/glauth@v2.0.0
go get: github.com/glauth/glauth@v2.0.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```
This happens because the module path in your `go.mod` file is missing the `/v2` suffix. This is necessary for the Go module system. See https://go.dev/blog/v2-go-modules#publishing-v2-and-beyond-h2 for more information.

Could we resolve those issues? I would appreciate it a lot since we are stuck at a version which the dependabot can't resolve and therefor can't finish the scans in our repo.

/cc @butonic

**Comment by Fusion** [comment]
So, I *think* that you could check whether what I've done works with:

```
go get github.com/glauth/glauth/v2@ef3151c28733c25bb3b5e539e8c6300ef850fad4
```

In theory, this is V2, latest commit. I have not assigned any tag yet.

**Comment by wkloucek** [comment]
> So, I _think_ that you could check whether what I've done works with:
> 
> ```
> go get github.com/glauth/glauth/v2@ef3151c28733c25bb3b5e539e8c6300ef850fad4
> ```
> 
> In theory, this is V2, latest commit. I have not assigned any tag yet.

Thank you for your quick help :-)

Confirmed, that the import works without problems: https://github.com/owncloud/ocis/pull/2656
