### ISSUE TITLE
Restrict service login

### ISSUE THREAD

**Issue by splitice** [glauth/glauth#231]
One thing I've noticed that is missing is a differentiation between users being served (for whatever systems are being authenticated for) and access to the LDAP server. 

I went about building this into my fork (https://github.com/splitice/glauth/commit/dbc0fceeae5c3172a32e63cade7f504a1069f5bd) however this isnt a configurable method of doing this.

Unfortuantely there isnt with the current API an easy way to get the group object from the user object so i was forced to operate on the group name directly (rather than adding a boolean value to the group configuration)

**Comment by Fusion** [comment]
Hi. Are you referring to the fact that not all users should be able to search the server?
If so, can you have a look at [capabilities](https://glauth.github.io/docs/capabilities.html) and share your thoughts?

**Comment by splitice** [comment]
yes, whem that merges it will do what is expected

I do think it would be more convenient to specify it at the group level (all members of this group are service accounts)

**Comment by Fusion** [comment]
A valid point. Right now, we expect clients to use groups to determine access, so it would make sense for the server itself to also follow this pattern.

**Comment by splitice** [comment]
This is complete in v2.
