### ISSUE TITLE
Some small errors in the documentation about using the plugin

### ISSUE THREAD

**Issue by go-goll** [glauth/glauth#235]
![image](https://user-images.githubusercontent.com/47687425/142149323-2d67790a-5083-49aa-bda1-737e4166b2f4.png)
As shown in the figure, the writing of SQL seems to be irregular, which will cause the DB to not be parsed. This is just a small problem. It would be great if you can fix it.

**Comment by Fusion** [comment]
Wow. Eagled eyed you are.

Yes I need to fix this. I cannot unsee it now.
