### ISSUE TITLE
dn attribute contains too many "ou=" things

### ISSUE THREAD

**Issue by hellerbarde** [glauth/glauth#246]
### Regression 2.0.0 -> 2.1.0-rc1

The dn reported by a search query contains 2 ou= thingies, both for the primary group and another group called "users". Like this: `cn=hellerbarde,ou=superheros,ou=users,dc=example,dc=com` 

This dn is then used as a binddn, which gets rejected by glauth. See this log excerpt:

```
12:59:22.641675 Bind ▶ DEBU 009  "level"=6 "msg"="Bind request"  "basedn"="dc=example,dc=com" "binddn"="cn=hellerbarde,ou=superheros,ou=users,dc=example,dc=com" "src"={"IP":"127.0.0.1","Port":40340,"Zone":""}
12:59:22.641726 findUser ▶ WARN 00a  "level"=2 "msg"="BindDN should have only one or two parts"  "binddn"="cn=hellerbarde,ou=superheros,ou=users,dc=example,dc=com" "numparts"=3
```

I had this problem with both [gitbucket](https://github.com/gitbucket/gitbucket) and [dex](https://dexidp.io/docs/getting-started/)

I don't know enough LDAP-lingo to properly explain what's happening, but I'm assuming that the "users" group is implicit to all users?

In any case, I tried to find the code that returns the dn attribute but I couldn't figure it out. :smile: 

I also mentioned this in the matrix channel, but I figured a proper bug report couldn't hurt.

**Comment by hellerbarde** [comment]
To be 100% clear: The same setup, config and everything worked again by just replacing the 2.1.0-rc1 binary with the 2.0.0 release binary.

**Comment by hellerbarde** [comment]
I got around to testing this, and the preview binary provided by "chrisfr" on the Matrix channel definitely fixed this. Thanks a lot for the effort

**Comment by hellerbarde** [comment]
@Fusion I'm guessing you're chrisfr on Matrix. Just so you see this.

**Comment by hellerbarde** [comment]
Also, I probably shouldn't close this quite yet. that was my mistake. Sorry.

**Comment by Fusion** [comment]
Thanks @hellerbarde yes that's me. Good to know that I was able to "undo" the breaking change :)
