### ISSUE TITLE
编译通过以后，运行报错

### ISSUE THREAD

**Issue by zhangyongquanpt** [glauth/glauth#247]
![image](https://user-images.githubusercontent.com/37578583/146854211-cde20241-c4ac-421e-bf9a-53fe69ccd073.png)

麻烦帮忙看看什么问题

**Comment by nomandera** [comment]
From google translate "Trouble help see what's wrong"

**Comment by Fusion** [comment]
(Thanks @nomandera !) .

@zhangyongquanpt -> This means that you have both a `[backends]` directive (still valid for backward compatibility) and a `[[backends]]` directive in your configuration file. Simply get rid of either one.
