### ISSUE TITLE
Use-Case: Self Service management of an existing LDAP infrastructure like AD?

### ISSUE THREAD

**Issue by prologic** [glauth/glauth#249]
I'm curious about a particular user-case I have in mind:

Basically as per the title.

Is it possible to use Glauth with an existing LDAP backend such as Microsoft AD to effectively provide interna self-service management for users such as "Changing their password"?

Thanks!

**Comment by Fusion** [comment]
HI @prologic . Sorry, this is definitely not a use case for GLAuth.
