### ISSUE TITLE
LDAP Result Code 49 - BindDN should have only one or two parts

### ISSUE THREAD

**Issue by greenpau** [glauth/glauth#252]
I working on the integration with GLAuth in https://github.com/greenpau/caddy-security/issues/32

The LDAP library used is `github.com/go-ldap/ldap/v3 v3.4.1`.

Working with the `sample-simple.cfg` provided in the getting started.

The binding does not quite work.

As user. I get: `LDAP Result Code 49 "Invalid Credentials": `

In GLAuth logs I see: `BindDN should have only one or two parts` 

```
18:11:40.997631 Bind ▶ DEBU 023  "level"=6 "msg"="Bind request"  "basedn"="dc=glauth,dc=com" "binddn"="cn=serviceuser,ou=svcaccts,dc=glauth,dc=com" "src"={"IP":"127.0.0.1","Port":56898,"Zone":""}
18:11:40.997681 Bind ▶ DEBU 024  "level"=6 "msg"="Bind success"  "binddn"="cn=serviceuser,ou=svcaccts,dc=glauth,dc=com" "src"={"IP":"127.0.0.1","Port":56898,"Zone":""}
18:11:40.998060 Search ▶ DEBU 025  "level"=6 "msg"="Search request"  "basedn"="dc=glauth,dc=com" "binddn"="cn=serviceuser,ou=svcaccts,dc=glauth,dc=com" "filter"="(\u0026(|(uid=johndoe)(mail=johndoe))(objectClass=posixAccount))" "scope"=2 "searchbasedn"="dc=glauth,dc=com" "src"={"IP":"127.0.0.1","Port":56898,"Zone":""}
18:11:40.998076 searchMaybeTopLevelNodes ▶ DEBU 026  "level"=6 "msg"="Search request"  "special case"="top-level browse"
18:11:40.998131 searchMaybeTopLevelNodes ▶ DEBU 027  "level"=6 "msg"="AP: Top-Level Browse OK"  "filter"="(\u0026(|(uid=johndoe)(mail=johndoe))(objectClass=posixAccount))"
18:11:40.998388 Bind ▶ DEBU 028  "level"=6 "msg"="Bind request"  "basedn"="dc=glauth,dc=com" "binddn"="cn=johndoe,ou=superheros,ou=users,dc=glauth,dc=com" "src"={"IP":"127.0.0.1","Port":56898,"Zone":""}
18:11:40.998404 findUser ▶ WARN 029  "level"=2 "msg"="BindDN should have only one or two parts"  "binddn"="cn=johndoe,ou=superheros,ou=users,dc=glauth,dc=com" "numparts"=3
```

Please assist.

**Comment by greenpau** [comment]
I think the issue is rooted in this code.

https://github.com/glauth/glauth/blob/e7195ed983715383bd5df1dc521f8c17d34d6a50/v2/pkg/handler/ldapopshelper.go#L601-L612

The `johndoe` DN is `cn=johndoe,ou=superheros,ou=users,dc=glauth,dc=com`.

Once you strip the base dn, you are left with `cn=johndoe,ou=superheros,ou=users`.

https://github.com/glauth/glauth/blob/e26219c2f402021df8cf7a1bbcfc0c5ba984590a/sample-simple.cfg#L36

The `cn=johndoe,ou=superheros,ou=users` will have 3 parts, as opposed to two.

Thus, the logic would never pass when you have many nested groups.

**Comment by Fusion** [comment]
Sorry it took me a few days to reply. Can you test this executable? It should address the issue (you are the second user reporting it and it's a real regression):

https://file.io/vfSQH4zQnVs3

**Comment by greenpau** [comment]
> Sorry it took me a few days to reply. Can you test this executable? It should address the issue (you are the second user reporting it and it's a real regression):

@Fusion , this one works 👍

**Comment by joace** [comment]
@Fusion seems the bootleg in that share has been deleted, does that mean the official release with fix will be published soon? Or can you share another link to download the fix, so I can try on my setup, thanks!

**Comment by Fusion** [comment]
@joace if you are curious, I am awaiting another confirmation that this version works. You should be able to download it from https://mega.nz/file/ltgVhQJT#Kc9OBPGABc2Z1XrTFcDEXi8KGOjNwD8-SvR_emzePPg

**Comment by greenpau** [comment]
@Fusion , just a side note ... what is the user is not in `ou=users` and the OU is deeply nested?

**Comment by joace** [comment]
> @joace if you are curious, I am awaiting another confirmation that this version works. You should be able to download it from https://mega.nz/file/ltgVhQJT#Kc9OBPGABc2Z1XrTFcDEXi8KGOjNwD8-SvR_emzePPg

@Fusion thanks for the new link! Currently I'm running glauth in a container, but definitely a novice here, trying to figure out how to get new binaries into container and persist them.

**Comment by joace** [comment]
@Fusion I can report back that the bootleg (build: 20220130_213326Z) also worked in my setup, the previous "msg"="BindDN should have only one or two parts" issue fixed, I can login via ldap authentication.

**Comment by lbarnkow** [comment]
@Fusion Any idea when the fix to the `BindDN should have only one or two parts` is generally available in a proper release?

**Comment by Fusion** [comment]
I am thinking this week-end, as I got confirmation from multiple sources that the fix works well.

**Comment by lbarnkow** [comment]
@Fusion I managed to build my own binary off of the `dev` branch on my `linuxarm64` machine using the `docker.io/golang:bullseye` image. So I'm no longer in need for a timely official release.

However, I feel the whole CI/CD setup for glauth _should_ be tweaked a little to allow for more frequent releases. I haven't dug into it too much, but from the looks of it your current release process is not well-documented and seems to run on a personal / local machine. (I have no Golang experience)

I think it would be nice to rethink the branching approach for this repo and automate all of the build/publish steps. That way maintainers could focus on their code and reviewing/merging pull requests, while building and publishing releases is handled by a CI pipeline. If there is any interest within the glauth project I would gladly contribute. I have some experience with self-managed Jenkins and Drone CI pipeline, as well as, Travis CI (though they seem to have removed their free OSS offerings) and should be apply to apply this to other offerings like GitHub Actions or Circle CI, too.

I realize that this is kind of off-topic for this specific Issue, but I thought I'd test the waters before starting a new seperate Issue (Feature Request / Improvement Request).

By no means am I trying to bash the current workflow or the maintainers. English is not my first language, so if any of my remarks are impolite (or worse), please let me know. :heart:

**Comment by Fusion** [comment]
Hi Lorenz, thanks for taking the time to think about this in depth.

Regarding feeling stupid, the only reference I could find in our own documentation of the move to github workflows is on that page: https://glauth.github.io/docs/running-travis-ci-locally.html and is a mere reference to the process so don't feel bad.

i wish we could release more often and with more confidence as, even going through the automated workflow and unit tests, there is still room for improvement. At this time, we rely on a two-step process:

- When we think that we are ready for production, we create a "preview" release (that goes through automation workflows, of course)
- If issues are reported, we fix them in unofficial builds and wait for the impacted folks to report victory. Since they have their own stuff to worry about, it may take them a while to find the time to test the builds.

Since stability is a higher priority that improvements (GLAuth 's use case seems to have organically evolved to support orgs in production), this process means that releases are both meatier and less frequent (the former due to the latter)

**Comment by joace** [comment]
@Fusion Is there any plan to update docker image with v2.1.0 release?
