### ISSUE TITLE
Possible Spring security ldap compatibility issue

### ISSUE THREAD

**Issue by Megagyger** [glauth/glauth#259]
While using this image to replace replace red hats IDM on local, I have encountered an issue relating to the dirContextAdaptor user searchResult response

Below is my config
` 
[backend]
  datastore = "config"
  baseDN = "cn=accounts,dc=myorg,dc=com"
  
 [[users]]
  name = "user1"
  uidnumber = 1234
  primarygroup = 1234
  passsha256 = "passphrase"

[[users]]
  name = "userb"
  uidnumber = 1235
  primarygroup = 1235
  passsha256 = "passphrase"

[[groups]]
  name = "mygroup"
  gidnumber = 1234

[[groups]]
  name = "services"
  gidnumber = 1235`
`
  
With a userSearch and filter config like below
`
 ctxBaseDn: dc=myorg,dc=com
 filter: (uid={0})
 base: cn=users,cn=accounts
 searchControls: searchScope=2
 `

The response I get back with the one **searchResult** of **DirContextAdapter** consists of 
`dn: cn=user1,ou=mygroup,dc=myorg,dc=com
 base: ""` 
 
This is in contrast to the exact same **searchResponse** from the real IDM
` dn: cn=user1,ou=mygroup
 base: cn=accounts,dc=myorg,dc=com`

 
Any ideas why there is a difference here and why the user dn contains the baseDn and also why the baseDn is empty?

**Comment by Fusion** [comment]
Thanks for including your config. This will help me figure out what the issue may be.

**Comment by Megagyger** [comment]
If it helps please see also the string response of the serachResult for both glauth and original IDM

GLAUTH
`
(not relative)ldap://ldap:389/cn=user1,ou=mygroup,dc=myorg,dc=com: org.springframework.ldap.core.DirContextAdapter:org.springframework.ldap.core.DirContextAdapter: dn=cn=user1,ou=mygroup,dc=myorg,dc=com {objectClass[0]=posixAccount, objectClass[1]=shadowAccount}:No attributes`

ORIGINAL
`
org.springframework.ldap.core.DirContextAdapter: dn=uid=user1,cn=users,cn=accounts {someAtts, objectClass[0]=top, objectClass[1]=person, objectClass[2]=organizationalperson, objectClass[3]=inetorgperson, objectClass[4]=inetuser, objectClass[5]=posixaccount, objectClass[6]=krbprincipalaux, objectClass[7]=krbticketpolicyaux, objectClass[8]=ipaobject, objectClass[9]=ipasshuser, objectClass[10]=ipaSshGroupOfPubKeys, objectClass[11]=mepOriginEntry, loginShell=/bin/bash, moreAtts and memberOf groups}
`

**Comment by Megagyger** [comment]
@Fusion  Did you get a chance to investigate this? I

**Comment by Fusion** [comment]
I am not familiar with Spring so I am not quite sure how to help. However, from what you pasted, it looks like your question would end ip being to `group,myorg,com` and GLauth would reject that, especially since you would be logged in using the full path. I would expect your query to work if it was against `group,accounts,myorg,com`
