### ISSUE TITLE
memberOf broken in v2

### ISSUE THREAD

**Issue by splitice** [glauth/glauth#267]
Regression v1 -> v2 (master)

Did a test upgrade to v2. Unfortunately found a regression.

Query as follows:
```
ldapsearch -H ldap://ldap:389 -D cn=serviceuser,ou=svcaccts,dc=blah,dc=net -w nicetrynotmypassword -x -bdc=blah,dc=net -o nettimeout=2 '(memberof=ou=Administrator,ou=groups,dc=blah,dc=net)'
```

Returns no results.

Only change in configuration from v1 is the addition of "*" search capabilities.

```
[... serviceuser...]
        [[users.capabilities]]
        action = "search"
        object = "*"
[...]
```

No issue searching when querying for other attributes (say all active accounts). It's just memberOf broken.

User is a member of the group

```
# splitice, Administrator, users, blah.net
dn: cn=splitice,ou=Administrator,ou=users,dc=blah,dc=net
[...]
memberOf: ou=Administrator,ou=groups,dc=blah,dc=net
[...]
```

**Comment by splitice** [comment]
Please note I have confirmed the v2 configuration on v1 (as I have reverted) as working.

**Comment by Fusion** [comment]
Thanks for the comprehensive report. I am looking into this.  I may have follow-up questions soon.

**Comment by Fusion** [comment]
Can you email me your (anonymized) configuration file at chris [at] zteo.com? With my own config files, I am not seeing this issue.

**Comment by Fusion** [comment]
Flagging as stale.
