### ISSUE TITLE
PagedError: missing paged control 

### ISSUE THREAD

**Issue by dayadev** [glauth/glauth#272]
I am trying to do the search on the ldap server with `sample-simple.cfg` ldap data with I get the below error.

`stack=Error: LDAP search at DN "dc=glauth,dc=com" failed; caused by Error: undefined PagedError: missing paged control`

Cant seem to figure out from logs as below.

`13:52:03.084017 Bind ▶ DEBU 006  "level"=6 "msg"="Bind request"  "basedn"="dc=glauth,dc=com" "binddn"="cn=serviceuser,ou=svcaccts,dc=glauth,dc=com" "src"={"IP":"127.0.0.1","Port":49966,"Zone":""}
13:52:03.084150 Bind ▶ DEBU 007  "level"=6 "msg"="Bind success"  "binddn"="cn=serviceuser,ou=svcaccts,dc=glauth,dc=com" "src"={"IP":"127.0.0.1","Port":49966,"Zone":""}
13:52:03.088732 Search ▶ DEBU 008  "level"=6 "msg"="Search request"  "basedn"="dc=glauth,dc=com" "binddn"="cn=serviceuser,ou=svcaccts,dc=glauth,dc=com" "filter"="(objectclass=*)" "scope"=0 "searchbasedn"="" "src"={"IP":"127.0.0.1","Port":49966,"Zone":""}
13:52:03.088785 searchMaybeRootDSEQuery ▶ DEBU 009  "level"=6 "msg"="Search request"  "special case"="root DSE"
13:52:03.088906 searchMaybeRootDSEQuery ▶ DEBU 00a  "level"=6 "msg"="AP: Root Search OK"  "filter"="(objectclass=*)"
13:52:03.091463 Search ▶ DEBU 00b  "level"=6 "msg"="Search request"  "basedn"="dc=glauth,dc=com" "binddn"="cn=serviceuser,ou=svcaccts,dc=glauth,dc=com" "filter"="(objectClass=posixAccount)" "scope"=2 "searchbasedn"="dc=glauth,dc=com" "src"={"IP":"127.0.0.1","Port":49966,"Zone":""}
13:52:03.091488 searchMaybeTopLevelNodes ▶ DEBU 00c  "level"=6 "msg"="Search request"  "special case"="top-level browse"
13:52:03.091527 searchMaybeTopLevelNodes ▶ DEBU 00d  "level"=6 "msg"="AP: Top-Level Browse OK"  "filter"="(objectClass=posixAccount)"`

Looking for any suggestions on fixing this. Thank you!

**Comment by dayadev** [comment]
I think this is because the ldap server doesnt handle pagination. Is there a way we can enable to handle pagination?

**Comment by Fusion** [comment]
Hi @dayadev what client library are you using? This extension is, indeed, not supported at this time. However, the server should simply ignore it and return all records (not ideal for your use case, I guess!)
It doesn't look like your client checks the root DN for an extension listing, so I am not sure how it detects the lack of support.

**Comment by Fusion** [comment]
I will close this issue in a week if it does not get any further replies. Thank you.
