### ISSUE TITLE
database schema?

### ISSUE THREAD

**Issue by bodsch** [glauth/glauth#280]
I would like to support different backends in my [Ansible role](https://github.com/bodsch/ansible-glauth).

I am currently looking for documentation on the database schema, but have not been able to find anything.
The only thing I could find were sample statements to import demo data:
https://glauth.github.io/docs/databases.html

Is there a working and documented schema?

Regards

**Comment by Fusion** [comment]
It's a valid question.
While the database schema is straightforward, it has not been officially documented beyond the `plugins` (https://github.com/glauth/glauth/tree/master/v2/pkg/plugins) directory itself.
I'll try to get this squared out. No promise that it will happen this week, but it's definitely something I would like to add.

**Comment by Fusion** [comment]
First attempt: https://glauth.github.io/docs/databases.html (scroll down a bit)

**Comment by bodsch** [comment]
thanks. <3
and now the real SQL statements? ;)

**Comment by Fusion** [comment]
Oh, the database statements are straightforward. Take a look at `https://github.com/glauth/glauth/blob/master/v2/pkg/plugins/mysql.go` for instance to see the statements used to create the database.

**Comment by bodsch** [comment]
I'll try my hand at sqlite support.
The rest should then run similarly.

Thank you!
