### ISSUE TITLE
What is the correct backend integration?

### ISSUE THREAD

**Issue by bodsch** [glauth/glauth#282]
I found different notations in the documentation and in the examples:
(https://github.com/glauth/glauth/blob/master/v2/scripts/docker/default-config-plugins.cfg / https://glauth.github.io/docs/sqlite.html)

[[backends]] or [backend].

Can both notations be used?

**Comment by Fusion** [comment]
Both notations can be used.

`[backend]` was the original notation and is being kept around for compatibility purposes. But, under the hood, it gets converted to a single `[[backends]]` entry (used to specify multiple backends if needed)
