### ISSUE TITLE
bcrypt implementation?

### ISSUE THREAD

**Issue by bodsch** [glauth/glauth#293]
I have problems understanding the bcrypt implementation. :(
A password I generated has the following structure:
`$2y$2^<number of rounds>$<salt>$<hash>`

e.g: `$2a$12$vXQCX9zGGAj22vNazNrBz.pBCWsUuLH.QBLImlra61i70D/MFDhKa`

But it does not match the one in one of the commis or the documentation:

```
# bcrypt format: hex($2y$2^<number of rounds>$<salt>$<hash>)
  passappbcrypt = [
    "243261243130244B62463462656F7265504F762E794F324957746D656541326B4B46596275674A79336A476845764B616D65446169784E41384F4432" # dogood
  ]
```

When I integrate my (standard) bcrypt string, a client cannot connect glauth.   :(

What kind of witchcraft do I have to throw at my bcrypt string to make it work?

**Comment by Jonny007-MKD** [comment]
In the config file the password is "encoded" in hexadecimal numbers, i.e. each character is replaced by to characters from 0-9 and A-F.

On Linux, you can decode the above string "24326..." with
`echo "24326..." | xxd -r -p`
This gives me:
    $ echo "243261243130244B62463462656F7265504F762E794F324957746D656541326B4B46596275674A79336A476845764B616D65446169784E41384F4432" | xxd -r -p
    $2a$10$KbF4beorePOv.yO2IWtmeeA2kKFYbugJy3jGhEvKameDaixNA8OD2

The output is the bcrypt format as specified. For the 2a vs. 2y prefix have a look at https://stackoverflow.com/a/36225192.

**Comment by bodsch** [comment]
@Jonny007-MKD Thanks for the great explanation!
I will include this in my role documentation.

**Comment by bodsch** [comment]
Who should not have installed xxd: https://command-not-found.com/xxd
