### ISSUE TITLE
How to enable SQLite in container?

### ISSUE THREAD

**Issue by cpach** [glauth/glauth#299]
**When running the container _glauth/glauth:v2.1.0_, how do I enable the SQLite backend?**

Is _sqlite.so_ available inside that container? If so, in what location?

My configuration file looks like this:

```
[ldap]
  enabled = true
  listen = "0.0.0.0:389"

[ldaps]
  enabled = false

[backend]
  datastore = "plugin"
  plugin = "sqlite.so"
  pluginhandler = "NewSQLiteHandler"
  database = "/app/config/gl.db"
  baseDN = "dc=contoso,dc=com"
  nameformat = "cn"
  groupformat = "ou"
```

When I try to start the container I get this error message:

```
Version and build information:

GLauth v2.1.0

Build time: 20220507_185412Z
Commit: 5d79fd9b03b20fca32b3fad9d60e6f3330610e3b


Starting GLauth now.

14:42:31.722597 startService ▶ ERRO 001  "error"="Unable to load specified backend plugin: plugin: not implemented" "msg"="Could not create server"

GLauth has exited.
Exiting.
```

**Comment by traverseda** [comment]
Use `glauth/glauth-plugins` not `glauth/glauth` as your container image.

**Comment by Fusion** [comment]
Thanks @traverseda.
@cpach does this answer your question?

**Comment by traverseda** [comment]
I always try to close at least one issue when I open one :p

**Comment by cpach** [comment]
@traverseda @Fusion Aha. Thank you guys! Then I’ll use that container instead.
