### ISSUE TITLE
Implement Password Salting and Hash Incrementing

### ISSUE THREAD

**Issue by benyanke** [glauth/glauth#3]
_From @benyanke on April 19, 2018 17:28_

Should switch to salt+hash. However, needs to be backwards compatible. 

May also include a CLI option for generating passwords.

_Copied from original issue: nmcclain/glauth#18_

**Comment by ColonelThirtyTwo** [comment]
Should use a dedicated password algorithm like bcrypt or argon2.

A single round of sha256 is only somewhat better than plaintext. It's definitely weaker than the norm.

**Comment by Fusion** [comment]
- be sure to use one-tine salts to avoid compromising all passwords if a single one gets reversed
- backward compatibility shouldn't be an issue if using bcrypt: the newer scheme would generate hashes starting with "$2y$"

**Comment by Fusion** [comment]
Added bcrypt support in #195
