### ISSUE TITLE
Database schema docs do not match reality

### ISSUE THREAD

**Issue by traverseda** [glauth/glauth#301]
On the database schema page [here](https://glauth.github.io/docs/databases.html) the diagram shows that user.primarygroup is a pointing at a groups **id** field, in reality it points at the group's **gidnumber**. I'm currently building an app on top of glauth's database integration and that makes me a bit nervous. Is that the schema you're sticking with for sure?

**Comment by Fusion** [comment]
Thank you! You found a misleading picture in the documentation. Serves me for trying to automate creating this picture.

Yes, you should feel free to ignore the `id` column as both users and subgroups maintain relationships through `gidnumber` and there is no plan to change that.

**Comment by Fusion** [comment]
Quick additional comment: I am reworking the diagram and found the same issue with capabilities. They are, of course, matched against `uidnumber`!

**Comment by traverseda** [comment]
Yep, I did figure that out :p
