### ISSUE TITLE
Bad link in quickstart

### ISSUE THREAD

**Issue by candlerb** [glauth/glauth#308]
https://glauth.github.io/docs/quickstart.html
links to https://github.com/glauth/glauth/blob/master/sample-simple.cfg which no longer exists

I believe this should now be https://github.com/glauth/glauth/blob/master/v2/sample-simple.cfg

**Comment by ArslanYM** [comment]
Where is the link to its docs repositary , I cant seem to find it.

**Comment by candlerb** [comment]
Maybe here?
https://github.com/glauth/glauth.github.io/blob/master/spacebook/content/pages/quickstart.md

**Comment by ArslanYM** [comment]
Thanks @candlerb

**Comment by ArslanYM** [comment]
I have fixed the issue in above mentioned PR. Please review @benyanke

**Comment by benyanke** [comment]
Lgtm, merges

**Comment by candlerb** [comment]
The old page is still being served though.

Maybe it needs to go through a compilation step to generate the HTML?
https://github.com/glauth/glauth.github.io/blob/master/docs/quickstart.html

```
...</li><li>Download the <a href="https://github.com/glauth/glauth/blob/master/sample-simple.cfg" target="_blank" rel="noopener noreferrer">example config file</a>.</li><li>...
```
