### ISSUE TITLE
Build all final binaries through travis CI - add build info

### ISSUE THREAD

**Issue by benyanke** [glauth/glauth#32]
Add some build-time variables to include build info, such as:

git commit hash built from
pipeline number
version number
timestamp
tag number (ie, version?)

**Comment by benyanke** [comment]
Partially done in the dev branch.

**Comment by benyanke** [comment]
Build is fully working for version string in travis, as per this build:

https://travis-ci.org/glauth/glauth/jobs/406513562


Now just need to get it to copy the final binaries off to the draft GH release on a tag.

**Comment by butonic** [comment]
fixed with v1.1.2
