### ISSUE TITLE
Fix for #246 and #252 breaks when changing groupformat

### ISSUE THREAD

**Issue by andreasbruckmeier** [glauth/glauth#321]
The fix for #246 and #252 (https://github.com/glauth/glauth/pull/254/commits/ceefc66dbba9ae054958269825de31d22d30e262) breaks, when one changes the groupformat to something else than "ou".

The reason is, that the automatically appendend dn part "ou=users" is not affected by groupformat
https://github.com/glauth/glauth/blob/6a58f35b1426e18b47a8460de18cc16fc32c2199/v2/pkg/handler/ldapopshelper.go#L580
but the new condition for longer bind DNs assumes it
https://github.com/glauth/glauth/blob/6a58f35b1426e18b47a8460de18cc16fc32c2199/v2/pkg/handler/ldapopshelper.go#L626

I suggest to keep a hardcoded "ou=users" in the condition as long as "ou=users" is hardcoded in the other places.

**Comment by Fusion** [comment]
Ah. I should have known. I was very hesitant to touch the `ou` code (https://github.com/glauth/glauth/pull/312) and now you helped me remember why!

My knee-jerk reaction would be to make `ou` configurable everywhere. However, I do not think that this was my original intent: while the groupname itself can be configurable (e.g. `ou` or `cn') it seems incorrect to allow `users` and `groups` to be common names, so I am going to follow your recommendation.
I think I was being overzealous when I wrote this code.

**Comment by Fusion** [comment]
Two weeks already!

@andreasbruckmeier quick code review? https://github.com/glauth/glauth/pull/323

**Comment by andreasbruckmeier** [comment]
@Fusion https://github.com/glauth/glauth/pull/323 looks fine for me

**Comment by Fusion** [comment]
Fixed by #323

**Comment by ag0n1k** [comment]
Any idea when it will be released as 2.2.1 or 2.3.0 ?

**Comment by k0ste** [comment]
> Any idea when it will be released as 2.2.1 or 2.3.0 ?

The 2.2.1 was tagged, but binary is not released yet. See #334
