### ISSUE TITLE
Having trouble understanding chaining, backends, and/or plugins

### ISSUE THREAD

**Issue by ianfixes** [glauth/glauth#331]
I've been reading the docs and codebase, but I'm having a tough time wrapping my head around how the different backends work.

My goal is to write an LDAP proxy that delegates to a "real" LDAP backend, and my thought was to try and leverage the existing functionality of GLauth for "[relaying a query](https://glauth.github.io/docs/file.html#:~:text=since%20you%20can%20chain%20backends%2C%20you%20could%20use%20this%20backend%20to%20specify%20two%2Dfactors%20secrets%20before%20relaying%20a%20query%20to%2C%20for%20instance%2C%20a%20LDAP%20backend%20where%20the%20same%20users%20already%20exist)".  I could imagine simply writing my own backend and somehow instantiating it with a `LdapSvc` object.But I can't find an instance of where this relaying behavior is implemented, and I can't find a `type BackendAPI interface {`.

How would you suggest that I lay out a project for an LDAP server that does nothing but intercept every request, perhaps emit a message to confirm that the code was called, and then respond with the result of forwarding the request to a different LDAP server?  (No configuration beyond the underlying server's address really needs to be provided here -- I could read it from the CLI -- because the underlying LDAP server is going to handle all of that.)  Am I describing a plugin? A backend?  An LDAP proxy that simply _happens_ to use GLauth code?

Alternatively, what documentation have I failed to find & read that might answer these questions for me?

**Comment by Fusion** [comment]
What you are looking for is a datastore implementing the Handler interface. For instance, to pass through to a backing LDAP server, you use the datastore in `pkg/handler/ldap.go` 
It offers the functionalities described in the Binder, Searcher, etc. wrapped interfaces, and when receiving a query, passes it to the upstream backend that has the best response time.
This is how GLAuth offers MFA injection, for instance.

**Comment by ianfixes** [comment]
Thanks for your reply! 

It looks like `nmcclain/ldap` is a closer approximation of the module I need to be working with to accomplish what I need to do.
