### ISSUE TITLE
Build Integration Testing for S3 reading

### ISSUE THREAD

**Issue by benyanke** [glauth/glauth#37]
Minio could be of use. Should, ideally, be part of a CI system.

While Travis can't do external docker containers, I believe, perhaps a new CI system could handle.

Of course, in the meantime, a subpar but workable solution would be hosting a known file on s3 and running tests against that.

**Comment by lukasmrtvy** [comment]
Any progress on this ? Thanks

**Comment by Fusion** [comment]
Fixed by #329
