### ISSUE TITLE
Git build info missing

### ISSUE THREAD

**Issue by shipperizer** [glauth/glauth#388]
It seems the change https://github.com/glauth/glauth/commit/114b36f677a494422d278e4a8a0a21de8d659c19 that have been introduced in there removed the `-buildvcs` modifier on the build

not sure if that was intended, but without that the methods from `runtime/debug` won't be able to collect any information

**Comment by Fusion** [comment]
This change does not show a removal of buildcvs. I would not have removed it knowingly. Let me figure out what happened there.

**Comment by Fusion** [comment]
It looks like it happened  here: https://github.com/shipperizer/glauth/commit/f474f883d4861eb0f27a100694e5c42781be743c

Perhaps I botched that merge. Feel free to put it back in, or I'll do it myself. It's just a matter of removing `=false` correct?

**Comment by shipperizer** [comment]
that's correct, i think something got lost in the merge, i ll open a PR
