### ISSUE TITLE
100% CPU usage

### ISSUE THREAD

**Issue by FlorinPeter** [glauth/glauth#404]
Hey @Fusion,

First of all, thanks for this awesome project!

While I was testing the latest versions, I saw that the pods on my k8s cluster were running at 100% CPU load. 
I have spotted these lines as the root cause: https://github.com/glauth/glauth/blob/42c448f3c750049fdd51e4ecd6227168e2060ad2/v2/internal/monitoring/ldap.go#L24-L25

**Comment by Fusion** [comment]
Hi Florin,

I am a bit confused as to why these lines would cause the issue.
Granted, that `continue` statement doesn't appear necessary. But the loop will still run again, and wait on the ticker channel for 15 seconds.
Are you sure this  is the exact cause?

**Comment by FlorinPeter** [comment]
Hi Chris,

The problem lies in the structure of the loop. When there's no data available on m.syncTicker.C, the loop will keep iterating without any delay. This results in a tight loop where the program continuously checks for data on m.syncTicker.C, causing 100% CPU usage because the loop is not throttled or delayed in any way.

You only need to remove the default.
```
for {
    select {
    case tick := <-m.syncTicker.C:
        m.logger.Debug().Time("value", tick).Msg("Tick")
        m.storeMetrics()
    }
}
```
This approach ensures that the loop only proceeds when there's something to do, and it will effectively prevent the CPU from being overloaded by eliminating the tight loop caused by the default case.

**Comment by cfr-convoso** [comment]
Ohhhh sorry of course it's the `default:` path itself that turns into a spinlock 🤣 
Since @shipperizer is currently taking time off I'm gonna fix that myself.

**Comment by Fusion** [comment]
Alright. That would be one release v2.3.2 then 😄
