### ISSUE TITLE
Support for LDAP query of more than 1000 records

### ISSUE THREAD

**Issue by ebinpissac** [glauth/glauth#407]
I am using glauth as a proxy to an Active Directory.
I have an application (OpenText OTDS) which needs to sync the users from AD over LDAP. The number of users are more than 1000. When the application directly query the AD, they are able to retrieve the users, however, when query through glauth, it fails with error 
`handleSearchRequest error LDAP Result Code 4 "Size Limit Exceeded": LDAP Result Code 4 "Size Limit Exceeded"`

The application seems to be batching /paginating the query, but I suspect that glauth does not support it. Any suggestions on how this can be achieved ?

**Comment by ebinpissac** [comment]
If anyone is stuck with this issue, i managed to use nginx as a tcp proxy to AD and got this solved

**Comment by Fusion** [comment]
This is a very interesting comment, thank you.
Indeed, paging should be implemented as it is not right now. I have a few ideas how this could happen but I will need to create a pipeline so this will take some time.

**Comment by Fusion** [comment]
(Note to self: http://www.faqs.org/rfcs/rfc2696.html)

**Comment by Fusion** [comment]
Hi @ebinpissac I realize it's not going to be much help to you, but just letting you know that thanks to your input, this feature will be available in GLAuth's next release.
