### ISSUE TITLE
latest tag missing on docker hub

### ISSUE THREAD

**Issue by CodeWithMa** [glauth/glauth#443]
It seems like the `latest` tag is gone.
See https://hub.docker.com/r/glauth/glauth/tags?name=latest.
Is this intended? What should I use instead?

**Comment by Fusion** [comment]
Hi. Sorry about that, I did not mean to get rid of the "latest" tag.
I pushed it back to docker hub.
But it's a good question and in my opinion no-one would download the "latest" tag, regardless of project, glauth or other. Instead a specific tag should be used, for security reasons and stability. But it's just one person's opinion 😄

**Comment by CodeWithMa** [comment]
Thanks :)
I agree that in production one should pin a specific version but in my tests I like to pull the latest version so I can see breaking changes right away.
