### ISSUE TITLE
Add Configuration Option to Allow Annon Binding 

### ISSUE THREAD

**Issue by benyanke** [glauth/glauth#5]
_From @woopstar on November 14, 2017 10:2_

This needs to allow anon access to RootDSE for it to work as authentication backend for SSSd in CoreOS etc.

When you use SSSd it fails as it is not allowed to do an anon binding on the RootDSE

_Copied from original issue: nmcclain/glauth#5_

**Comment by benyanke** [comment]
_From @woopstar on January 1, 2018 19:23_

Or it should allow you to create a bind user for non-anon access btw

**Comment by benyanke** [comment]
> Or it should allow you to create a bind user for non-anon access btw

You can easily do that by just creating a user for the purpose of allowing binding, right?

**Comment by benyanke** [comment]
I do agree though - adding a boolean to allow annon binding would be good.

**Comment by Fusion** [comment]
Turns out, I recently added this flag to the configuration without realizing there was an issue opened.

Will be in 2.0 release.
