### ISSUE TITLE
How To Run as a Daemon

### ISSUE THREAD

**Issue by online-stuff** [glauth/glauth#78]
It should be a simple 'feature' for server software, but how does one run glauth as a daemon for startup on boot, or even just running in the background?

Along this idea..  Is it possible to write the debug data to a file?

**Comment by lathama** [comment]
For systemd you can create a service file 
https://www.freedesktop.org/software/systemd/man/systemd.service.html

Random example to build off of at https://github.com/go-gitea/gitea/blob/master/contrib/systemd/gitea.service

As far as the debug, what are you asking exactly?

**Comment by benyanke** [comment]
Sorry I didn't get this sooner - Andrew is correct. Daemonization is something outside the scope of the program itself, but can easily be handled with tools like systemd services, supervisor, or docker.

Similarly, the debug data outputs to STDOUT but that can easily be redirected by one of the aforementioned services to a file for you.
