### ISSUE TITLE
undefined: Asset

### ISSUE THREAD

**Issue by ijt** [glauth/glauth#87]
I'm trying to build glauth but it's failing like this:
```
[ ~/src/github.com/glauth/glauth ] go build
# github.com/glauth/glauth
./webapi.go:20:24: undefined: Asset
./webapi.go:45:22: undefined: Asset
[ ~/src/github.com/glauth/glauth ] echo $GO111MODULE 
on
```
Did someone check in broken code or do I just not know what I'm doing?

**Comment by ijt** [comment]
It compiles at an earlier version for me:
```
[ ~/src/github.com/glauth/glauth ] git checkout -b y 6a3f96c04d418403a8c8c88214679840176eff90
Switched to a new branch 'y'
[ ~/src/github.com/glauth/glauth ] go build
```

**Comment by icarus-sparry** [comment]
Asset was a function defined in bindata.go, which (according to the first few lines in it) is automatically generated by go-bindata from the 3 files in assets.

A simple fix appears to be adding "io/ioutil" to the list of imports, and

func Asset(name string) ([]byte, error){
    return ioutil,ReadFile(name)
}

**Comment by icarus-sparry** [comment]
The Asset function is defined in bindata.go. This file is created by `make bindata`

**Comment by DeepDiver1975** [comment]
This can be closed @butonic

**Comment by butonic** [comment]
run `make bindata` to get the generate the file
