### ISSUE TITLE
nextcloud support

### ISSUE THREAD

**Issue by halkeye** [glauth/glauth#90]
I'm trying to get glauth to work inside my home network with nextcloud.

I saw in #53 that it was working, but as of today i'm getting at least an error on intiial setup of ldap

```
glauth/glauth-6664bffb9d-h8nwk[glauth]: 03:35:31.916127 Search ▶ DEBU 185 Search request as cn=halkeye2,ou=users,dc=gavinmogan,dc=com from 10.244.1.189:43366 for (&(|(objectclass=posixGroup)(objectclass=group)(objectclass=zimbraDistributionList)(objectclass=groupOfNames)(objectclass=groupOfUniqueNames))(cn=*))
glauth/glauth-6664bffb9d-h8nwk[glauth]: 2019/08/20 03:35:31 handleSearchRequest error LDAP Result Code 1 "Operations Error": Search Error: unhandled filter type: groupofuniquenames [(&(|(objectclass=posixGroup)(objectclass=group)(objectclass=zimbraDistributionList)(objectclass=groupOfNames)(objectclass=groupOfUniqueNames))(cn=*))]
```

https://github.com/glauth/glauth/blob/28802ff87d5b59d7f7016d19ac50ff8f70b04945/configbackend.go#L186

Do we need to handle all types it might encounter, or is there a "meh" and ignore type feature?

**Comment by halkeye** [comment]
Oh, its looks like its the automatic detection dropdowns, so not that critical

Search from groups:
```
glauth/glauth-6664bffb9d-h8nwk[glauth]: 03:39:19.463026 Search ▶ DEBU 1aa Search request as cn=halkeye2,ou=users,dc=gavinmogan,dc=com from 10.244.1.189:47080 for (&(|(objectclass=posixGroup)(objectclass=group)(objectclass=zimbraDistributionList)(objectclass=groupOfNames)(objectclass=groupOfUniqueNames))(cn=*))
glauth/glauth-6664bffb9d-h8nwk[glauth]: 2019/08/20 03:39:19 handleSearchRequest error LDAP Result Code 1 "Operations Error": Search Error: unhandled filter type: groupofuniquenames [(&(|(objectclass=posixGroup)(objectclass=group)(objectclass=zimbraDistributionList)(objectclass=groupOfNames)(objectclass=groupOfUniqueNames))(cn=*))]
```

**Comment by halkeye** [comment]
ah so I figured it out, I found a random log line in next cloud complaining about a missing uuid attribute

Overriding everything makes it work :)

![image](https://user-images.githubusercontent.com/110087/63316443-c4f03a80-c2c3-11e9-8e4d-29f6238e45d6.png)

**Comment by DeepDiver1975** [comment]
I guess this can be closed now as well @butonic

**Comment by butonic** [comment]
closing as this is a config issue. If you need a uuid like attribute open a new issue, or better yet, a PR!
