### ISSUE TITLE
Support for LDAP with TLS?

### ISSUE THREAD

**Issue by pl89** [glauth/glauth#96]
Not to be confused with LDAP over SSL (LDAPS), does glauth support LDAP with TLS (StartTLS over ldap scheme)?
I unfortunately couldn't find any documentation on the subject (sorry if I'm blind) and couldn't get it to work... Configuration problem or simply trying to use a feature that doesn't exist?

**Comment by gkoh** [comment]
I looked, StartTLS isn't supported.
The underlying LDAP library (https://github.com/nmcclain/ldap) specifically mentions StartTLS isn't implemented.

**Comment by prologic** [comment]
But LDAP over SSL works?
-- 

James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by gkoh** [comment]
> But LDAP over SSL works?
Yes, I have it working.

**Comment by pl89** [comment]
LDAPS is unfortunately non-standard (at least based on my understanding) and START TLS is the preferred/standard way of operating. Might be exceptional but the system I am using only supports START TLS and not LDAPS (however, I have no visibility into how common that actually is).
Thanks @gkoh and @prologic!

**Comment by prologic** [comment]
What system out of curiosity? I get that LDAPS isn't standardized; however SSL is pretty transparent to pretty much most (_if not all_) applications really; even if the application doesn't directly support TLS you can always use things like `socat` :)

**Comment by unclesamwk** [comment]
Can anyone pls explain how configure glauth with ldap over ssl?

**Comment by gkoh** [comment]
> Can anyone pls explain how configure glauth with ldap over ssl?

My relevant configuration fragment resembles this:
```
[ldaps]
  enabled = true
  listen = "<hostname>:636"
  cert = /path/to/server.certificate
  key = /path/to/server.key
```

**Comment by poldi1405** [comment]
For some reason I get
```
2020/01/30 19:44:00 handleConnection ber.ReadPacket ERROR: remote error: tls: unknown certificate authority
```
When using a letsencrypt certificate... anyone has an idea what could be the reason for that?

Config:
```
[ldaps]
  enabled = true
  listen = "ldap.poldrack.me:636"
  cert = "/etc/letsencrypt/live/my.domain.com/cert.pem"
  key = "/etc/letsencrypt/live/my.domain.com/privkey.pem"
```

**Comment by mmguero** [comment]
If somebody needs this in a pinch, you could absolutely do this with stunnel, which supports this since mtrojnar/stunnel#13. I've done this before (not with glauth, but in front of an unencrypted OpenLDAP instance) and it worked fine.

**Comment by Fusion** [comment]
Thanks @mmguero if you do not mind I will use your example in the documentation pages. I did consider implementing StartTLS at the protocol level, but so far it's been possible to update the underlying protocol library without worrying about patch maintenance. I am not ashamed to admit that I like the convenience of not having to touch the library itself :)
