### ISSUE TITLE
Ansible role for glauth setup

### ISSUE THREAD

**Issue by egeneralov** [glauth/glauth#97]
Hello.

Thank for your work, it's awersome!
Please, review my ansible role for this project :)

https://github.com/egeneralov/glauth

Kind regards.

**Comment by DeepDiver1975** [comment]
Please submit a pull request and maintainers can review. THX

**Comment by Fusion** [comment]
Weird. Didn't find any ansible work.

@egeneralov feel free to re-open this if I am missing something.
