### ISSUE TITLE
Config backend should allow users to bind without specifying group name

### ISSUE THREAD

**Issue by chrisbrowning** [glauth/glauth#98]
Specifying a bindDN that does not contain an `ou=` term will return `Bind Error: Group  not found`, even though the same code conditionally checks for bind strings that [do not contain that second term](https://github.com/glauth/glauth/blob/dev/configbackend.go#L46-L54).

`groupName` is initiated with an empty value, and if you do not specify the `ou=` term, groupName does not get set in the previously-mentioned conditional block.

Because `groupName` does not get set, the backend will be unable to find the a matching groupname from the config file's groups. This search makes sense if you specify the `ou=` term but if you only provide the `cn=` you should still be able to bind.

**Comment by candlerb** [comment]
Updated link: https://github.com/glauth/glauth/blob/master/pkg/handler/config.go#L51-L59

The error actually has two spaces, showing that the group used is "" (empty string)

```
Bind Error: Group  not found.
```

I agree, it looks like the *intention* was to support bind without providing the group part of the DN, but this was not properly completed.
